<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rupali" failures="0" tests="5" name="IncludeExcludeinclasslevel.InEx1" time="0.175" errors="1" timestamp="2022-08-01T15:10:08 IST" skipped="0">
  <testcase classname="IncludeExcludeinclasslevel.InEx1" name="B" time="0.118">
    <error message="Method IncludeExcludeinclasslevel.InEx1.B() didn&#039;t finish within the time-out 100" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method IncludeExcludeinclasslevel.InEx1.B() didn't finish within the time-out 100
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- B -->
  <system-out/>
  <testcase classname="IncludeExcludeinclasslevel.InEx1" name="C" time="0.010"/>
  <system-out>
    <![CDATA[C is running]]>
  </system-out>
  <testcase classname="IncludeExcludeinclasslevel.InEx1" name="D" time="0.003"/>
  <system-out>
    <![CDATA[D is running]]>
  </system-out>
  <testcase classname="IncludeExcludeinclasslevel.InEx1" name="A" time="0.031"/>
  <system-out>
    <![CDATA[A is running]]>
  </system-out>
  <testcase classname="IncludeExcludeinclasslevel.InEx1" name="E" time="0.013"/>
  <system-out>
    <![CDATA[E is running]]>
  </system-out>
</testsuite> <!-- IncludeExcludeinclasslevel.InEx1 -->
